name: Release
on:
  push:
  release:
    types:
      - published

jobs:
  validate:
    runs-on: hadolint
    continue-on-error: true
    steps:
      - name: Setup
        run: |
          apt update
          apt install -y git nodejs
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Validate Dockerfile
        run: |
          hadolint Dockerfile | tee hadolint-result.xml

  build-deploy:
    runs-on: ubuntu-22.04
    container:
      image: catthehacker/ubuntu:act-latest
    needs: validate
    env:
      IMAGE_NAME: ecw74/photosync
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags:  ${{ env.IMAGE_NAME }}:latest
          no-cache: true
      - name: Deploy
        uses: docker/build-push-action@v6
        if: github.event_name == 'release'
        with:
          push: true
          tags:  ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
